---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# PredatorIsolationStochasticity

<!-- badges: start -->
<!-- badges: end -->

The goal of PredatorIsolationStochasticity is to walk the user through the data analyses shown in Pelinson et al. 2020B.

#### Here you can find the r code the run some of the results shown in the main paper for:

[Community Size](https://github.com/RodolfoPelinson/PredatorIsolationStochasticity/blob/master/Community%20Size%20Analyses/Community-Size-Analyses.md)  

[Alpha Diversity](https://github.com/RodolfoPelinson/PredatorIsolationStochasticity/blob/master/Alpha%20Diversity%20Analyses/Alpha-Diversity-Analyses.md)  

[Gamma Diversity](https://github.com/RodolfoPelinson/PredatorIsolationStochasticity/blob/master/Gamma%20Diversity%20Analyses/Gamma-Diversity-Analyses.md)  

[Community Variability](https://github.com/RodolfoPelinson/PredatorIsolationStochasticity/blob/master/Community%20Variability%20Analyses/Community-Variability-Analyses.md)  

  
\  
\  
\  


#### A deeper dive into the observed patterns (shown in the supplements) can be found in the following pages:

[Community Variability - Predatory and Non-Predatory Insects](https://github.com/RodolfoPelinson/PredatorIsolationStochasticity/blob/master/Community%20Variability%20-%20Pred%20and%20Non-Pred/Community-Variability-Analyses---Pred-and-Non-Pred.md). Here we repeat the analyses for community variability for predatory and non-predatory insects separetely.

[Community Variability - First Survey](https://github.com/RodolfoPelinson/PredatorIsolationStochasticity/blob/master/Community%20Variability%20-%20First%20Survey/Community-Variability---First-Survey.md). Here we repeat the analyses for community variability for the first survey of the experiment only. We let this one out of the main paper because it was to early in the assembly process.

[Community Variability - Allowing Gamma diversity to vary](https://github.com/RodolfoPelinson/PredatorIsolationStochasticity/blob/master/Community%20Variability%20-%20Varying%20Gamma/Community-Variability---Varying-Gamma.md). Here we repeat the analyses for community variability for the whole community, but allowing gamma diversity to vary among treatments.

[Community Variability - Different Null-Model algorithm](https://github.com/RodolfoPelinson/PredatorIsolationStochasticity/blob/master/Community%20Variability%20-%20Siqueira_2020/Community-Variability---Siqueira_2020.md). Here we repeat the analyses for community variability using the null-model algorithm used by [Siqueira et al 2020](https://doi.org/10.1002/ecy.3014).


